apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: produto
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: produto
    spec:
      containers:
      - name: produto
        image: micro_servico_produto:v1
        ports:
        - containerPort: 3000
